// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: Mail-Service/mail.proto

package mail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendTokenVerifyAccount(ctx context.Context, in *SendTokenVerifyAccountRequest, opts ...grpc.CallOption) (*SendTokenVerifyAccountResponse, error)
	SendTokenResetPassword(ctx context.Context, in *SendTokenResetPasswordRequest, opts ...grpc.CallOption) (*SendTokenResetPasswordResponse, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendTokenVerifyAccount(ctx context.Context, in *SendTokenVerifyAccountRequest, opts ...grpc.CallOption) (*SendTokenVerifyAccountResponse, error) {
	out := new(SendTokenVerifyAccountResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/SendTokenVerifyAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendTokenResetPassword(ctx context.Context, in *SendTokenResetPasswordRequest, opts ...grpc.CallOption) (*SendTokenResetPasswordResponse, error) {
	out := new(SendTokenResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/SendTokenResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility
type MailServiceServer interface {
	SendTokenVerifyAccount(context.Context, *SendTokenVerifyAccountRequest) (*SendTokenVerifyAccountResponse, error)
	SendTokenResetPassword(context.Context, *SendTokenResetPasswordRequest) (*SendTokenResetPasswordResponse, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (UnimplementedMailServiceServer) SendTokenVerifyAccount(context.Context, *SendTokenVerifyAccountRequest) (*SendTokenVerifyAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTokenVerifyAccount not implemented")
}
func (UnimplementedMailServiceServer) SendTokenResetPassword(context.Context, *SendTokenResetPasswordRequest) (*SendTokenResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTokenResetPassword not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendTokenVerifyAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTokenVerifyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendTokenVerifyAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SendTokenVerifyAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendTokenVerifyAccount(ctx, req.(*SendTokenVerifyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendTokenResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTokenResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendTokenResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SendTokenResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendTokenResetPassword(ctx, req.(*SendTokenResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mail.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTokenVerifyAccount",
			Handler:    _MailService_SendTokenVerifyAccount_Handler,
		},
		{
			MethodName: "SendTokenResetPassword",
			Handler:    _MailService_SendTokenResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Mail-Service/mail.proto",
}
