// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: Mail-Service/mail.proto

package mail

import (
	Error "github.com/hoangphuc28/CoursesOnline/Proto/Error"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestMail string `protobuf:"bytes,1,opt,name=destMail,proto3" json:"destMail,omitempty"`
	Subject  string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_Service_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_Service_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_Mail_Service_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Mail) GetDestMail() string {
	if x != nil {
		return x.DestMail
	}
	return ""
}

func (x *Mail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SendTokenVerifyAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail  *Mail  `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url   string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SendTokenVerifyAccountRequest) Reset() {
	*x = SendTokenVerifyAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_Service_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTokenVerifyAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTokenVerifyAccountRequest) ProtoMessage() {}

func (x *SendTokenVerifyAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_Service_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTokenVerifyAccountRequest.ProtoReflect.Descriptor instead.
func (*SendTokenVerifyAccountRequest) Descriptor() ([]byte, []int) {
	return file_Mail_Service_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendTokenVerifyAccountRequest) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *SendTokenVerifyAccountRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendTokenVerifyAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendTokenVerifyAccountRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SendTokenVerifyAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error.ErrorResponse `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendTokenVerifyAccountResponse) Reset() {
	*x = SendTokenVerifyAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_Service_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTokenVerifyAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTokenVerifyAccountResponse) ProtoMessage() {}

func (x *SendTokenVerifyAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_Service_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTokenVerifyAccountResponse.ProtoReflect.Descriptor instead.
func (*SendTokenVerifyAccountResponse) Descriptor() ([]byte, []int) {
	return file_Mail_Service_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendTokenVerifyAccountResponse) GetError() *Error.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type SendTokenResetPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *SendTokenResetPasswordRequest) Reset() {
	*x = SendTokenResetPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_Service_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTokenResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTokenResetPasswordRequest) ProtoMessage() {}

func (x *SendTokenResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_Service_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTokenResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*SendTokenResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_Mail_Service_mail_proto_rawDescGZIP(), []int{3}
}

func (x *SendTokenResetPasswordRequest) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type SendTokenResetPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error.ErrorResponse `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendTokenResetPasswordResponse) Reset() {
	*x = SendTokenResetPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_Service_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTokenResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTokenResetPasswordResponse) ProtoMessage() {}

func (x *SendTokenResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_Service_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTokenResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*SendTokenResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_Mail_Service_mail_proto_rawDescGZIP(), []int{4}
}

func (x *SendTokenResetPasswordResponse) GetError() *Error.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_Mail_Service_mail_proto protoreflect.FileDescriptor

var file_Mail_Service_mail_proto_rawDesc = []byte{
	0x0a, 0x17, 0x4d, 0x61, 0x69, 0x6c, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x1a,
	0x11, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x73, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65,
	0x73, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x7b, 0x0a, 0x1d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x4a, 0x0a,
	0x1e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x65, 0x72, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x1d, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x4a, 0x0a, 0x1e, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x72,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xd7, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x23, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x16, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x6f, 0x61, 0x6e, 0x67, 0x70, 0x68, 0x75, 0x63, 0x32, 0x38, 0x2f, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Mail_Service_mail_proto_rawDescOnce sync.Once
	file_Mail_Service_mail_proto_rawDescData = file_Mail_Service_mail_proto_rawDesc
)

func file_Mail_Service_mail_proto_rawDescGZIP() []byte {
	file_Mail_Service_mail_proto_rawDescOnce.Do(func() {
		file_Mail_Service_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_Mail_Service_mail_proto_rawDescData)
	})
	return file_Mail_Service_mail_proto_rawDescData
}

var file_Mail_Service_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Mail_Service_mail_proto_goTypes = []interface{}{
	(*Mail)(nil),                           // 0: mail.Mail
	(*SendTokenVerifyAccountRequest)(nil),  // 1: mail.SendTokenVerifyAccountRequest
	(*SendTokenVerifyAccountResponse)(nil), // 2: mail.SendTokenVerifyAccountResponse
	(*SendTokenResetPasswordRequest)(nil),  // 3: mail.SendTokenResetPasswordRequest
	(*SendTokenResetPasswordResponse)(nil), // 4: mail.SendTokenResetPasswordResponse
	(*Error.ErrorResponse)(nil),            // 5: err.ErrorResponse
}
var file_Mail_Service_mail_proto_depIdxs = []int32{
	0, // 0: mail.SendTokenVerifyAccountRequest.mail:type_name -> mail.Mail
	5, // 1: mail.SendTokenVerifyAccountResponse.error:type_name -> err.ErrorResponse
	0, // 2: mail.SendTokenResetPasswordRequest.mail:type_name -> mail.Mail
	5, // 3: mail.SendTokenResetPasswordResponse.error:type_name -> err.ErrorResponse
	1, // 4: mail.MailService.SendTokenVerifyAccount:input_type -> mail.SendTokenVerifyAccountRequest
	3, // 5: mail.MailService.SendTokenResetPassword:input_type -> mail.SendTokenResetPasswordRequest
	2, // 6: mail.MailService.SendTokenVerifyAccount:output_type -> mail.SendTokenVerifyAccountResponse
	4, // 7: mail.MailService.SendTokenResetPassword:output_type -> mail.SendTokenResetPasswordResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Mail_Service_mail_proto_init() }
func file_Mail_Service_mail_proto_init() {
	if File_Mail_Service_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Mail_Service_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_Service_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTokenVerifyAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_Service_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTokenVerifyAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_Service_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTokenResetPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_Service_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTokenResetPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Mail_Service_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Mail_Service_mail_proto_goTypes,
		DependencyIndexes: file_Mail_Service_mail_proto_depIdxs,
		MessageInfos:      file_Mail_Service_mail_proto_msgTypes,
	}.Build()
	File_Mail_Service_mail_proto = out.File
	file_Mail_Service_mail_proto_rawDesc = nil
	file_Mail_Service_mail_proto_goTypes = nil
	file_Mail_Service_mail_proto_depIdxs = nil
}
